admin_index :
    path: /index
    controller: App\Controller\AdminController::index

admin_users :
    path: /users
    controller: App\Controller\AdminController::users_list

admin_evaluations :
    path: /evaluations
    controller: App\Controller\AdminController::evaluations_list

admin_generer_evaluation :
    path: /generer_evaluation
    controller: App\Controller\AdminController::generer_evaluation

admin_generer_evaluation_suite :
    path: /generer_evaluation_suite
    controller: App\Controller\AdminController::generer_evaluation_suite

admin_supprimer_evaluation :
    path: /supprimer_evaluation/{id}
    controller: App\Controller\AdminController::supprimer_evaluation

admin_afficher_evaluation :
    path : /afficher_evaluation/{id}
    controller: App\Controller\AdminController::afficher_evaluation

admin_generer_fichier:
    path: /generer_fichier/{id}
    controller: App\Controller\AdminController::generer_fichier

admin_questions :
    path: /questions
    controller: App\Controller\AdminController::questions_list

admin_ajouter_questions :
    path: /ajouter_question
    controller: App\Controller\AdminController::ajouter_question

admin_supprimer_question :
    path: /supprimer_question/{id}
    controller: App\Controller\AdminController::supprimer_question

admin_ajouter_categorie :
    path: /ajouter_categorie
    controller: App\Controller\AdminController::ajouter_categorie

admin_ajouter_user :
    path: /ajouter_user
    controller: App\Controller\AdminController::ajouter_user

admin_modifier_user :
    path: /modifier_user/{id}
    controller: App\Controller\AdminController::modifier_user

admin_modifier_user_suite :
    path: /modifier_user_suite/{id}
    controller: App\Controller\AdminController::modifier_user_suite

admin_supprimer_user :
    path: /supprimer_user/{id}
    controller: App\Controller\AdminController::supprimer_user

admin_thematiques_matieres :
    path: /thematiques_matieres
    controller: App\Controller\AdminController::thematiques_matieres

admin_thematique_Supprimer:
    path: /Supprimer/{id}
    controller: App\Controller\AdminController::Supprimer

admin_matiere_Supprimer:
    path: /supprimer_matiere/{id}
    controller: App\Controller\AdminController::supprimer_matiere

admin_modifier_thematique:
    path: /modifier_thematique/{id}
    controller: App\Controller\AdminController::modifier_thematique

admin_modifier_matiere:
    path: /modifier_matiere/{id}
    controller: App\Controller\AdminController::modifier_matiere